### ISSUE TITLE
works fine off of 9443, 443/80 not so much

### ISSUE THREAD

**Issue by brunobulox** [chrisbeardy/nextcloud-docker-raspberrypi-tutorial#1]
Configures and runs fine off of port 9443.. does not work of standard ports.. swapped ports back and forth looking for typos in the yaml file but to no avail...

**Comment by brunobulox** [comment]
I'm a dweeb.. you expected to just NAT it together at the router .. wasn't exactly clear from
cut-----------
set up port forwarding

forward ports 80 and 443 on your router to point at the raspberry pi, port 80 is required later to get your TLS certificate. 
end cut -----------
You have to map 443 to 9443.. 

but cool thanks for the detail...

**Comment by chrisbeardy** [comment]
Thanks for the feedback, you should only have to forward port 80 to 80 and 443 to 443. Traefik should then take care of the rest.

**Comment by brunobulox** [comment]
Well that's not what I did.. I did 9443 -> 443 so something is not quite right.. It works but that's ugly .. I'm going to dig in a bit more , any ideas??..

**Comment by chrisbeardy** [comment]
Can you access from outside your network? 

E.g. 

HTTPS://example-domain.com

Because I would expect that request to go to the router on port 443. Hence mapping 443 of the router to 443 on the pi.

The 443 port should take you to Traefik which is the reverse proxy and that should then fetch nextcloud on port 9443. 

From inside your network using port 9443 from <ip-of-pi>:9443 may still work to get nextcloud up locally.

**Comment by brunobulox** [comment]
I get a page not found every time https://192.168.1.245/  - 404 page not found or externally when I have 443 mapped to 443 .. right now I have it mapped to 9443 externally and it works.. I am using guerillamedia.dyndns.org/ ... like I say, now it's mapped to 9443 internally ...

**Comment by chrisbeardy** [comment]
Ok. Tbh I'm not sure what's going on here. Let me know if you find a solution.

**Comment by KasperSkytte** [comment]
Thanks for this guide, it helped a long way, but I'm only nearly there. I have the same issue. I have to explicitly ask for port 9443 when connecting from both outside and inside, unless I do a port forwarding rule on my router 9443 -> 443. And that's a problem for me, cause I plan on using port 443 in the near future for a website. I don't exactly understand all the traefik settings in the docker-compose.yml, but to me it doesn't seem like anything is telling traefik to redirect port 443 to the nextcloud instance on port 9443?

**Comment by chrisbeardy** [comment]
I have to admit I am no expert on trafik and docker and mostly got this to work by following this tutorial. However, I've double checked my router settings, I am forwarding external port 443 to port 443 to the device running next cloud. I am not overlay familiar with the traefik settings however I believe the critical part is the labels.  The nextcloud service has been setup with the trafeik label telling it its port 443 (traefik.http.services.nextcloud.loadbalancer.server.port=443). The usual port the nextcloud service is set up the the service to use port 9443:443 which is why when directly forwarding your routers external port 443 to 9443 works to access Nextcloud however this then blocks further services using port 443. The trafik service has port 443:443 setup so should be intercepting the 443 traffic and then distributing it as its been setup to using the labels.

**Comment by chrisbeardy** [comment]
I don't think i'll be much help after this but I hope you managed to get it to work

**Comment by chrisbeardy** [comment]
OK I've been looking into this a bit more today, and it looks like this docker compose does not work nicely with the newer versions of nextcloud now. I would suggest looking at the updated nextcloud docker files: https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache/docker-compose.yml
